### PR TITLE
Fix unloadBeforeLoad prop to use billboardjs 'load' method

### LINKED ISSUE #2: Chart data not rendering properly when "unloadBeforeLoad" prop is used
Hi,

I've been trying to use **unloadBeforeLoad** prop to clean the chart data before loading new data and I think there's a problem.

The exact problem is that not every data is unloaded and I think it's because of this warning in **billboardjs** API: 
> **Unload**: Note: If you call load API soon after/before unload, unload param of load should be used. Otherwise chart will not be rendered properly because of cancel of animation.
[Source doc](https://naver.github.io/billboard.js/release/latest/doc/Chart.html#unload)

The exact point in react-billboardjs code is this code:

```js
if (unloadBeforeLoad) {
  instance.unloadData();
}

instance.loadData(data);
```

should be changed to

```js
instance.loadData({...data, unload: unloadBeforeLoad});
```
 https://github.com/planttheidea/react-billboardjs/blob/master/src/index.js#L209

I have fixed it in my local fork and it works perfect. 
I can submit a PR for you to review it and decide if you want to include the changes.

Cheers.

### PR DESCRIPTION
**Pull request by miguelCT**
Fix **unloadBeforeLoad** prop to use billboardjs 'load' method with 'unload' param instead of using 'unload' method.

fixes #2

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -206,11 +206,11 @@ export const createUpdateChart = (instance) => {
       instance.chart = instance.generateChart(props);
     }
 
+    instance.loadData({...data, unload: unloadBeforeLoad});
+
     if (unloadBeforeLoad) {
       instance.unloadData();
     }
```
Comment (planttheidea) [inline src/index.js]: based on the documentation provided, should this `if` statement still exist? wouldn't the call to `instance.loadData` that you've changed handle both the unload and the load of the data?
