### PR TITLE
Avoid legacy lifecycle warning

### LINKED ISSUE #34: Replace 'componentWillUpdate' to stop React warning about it
Hi, first of all, thanks to @planttheidea for this project and all the work that has been done here.

In my team we have recently upgraded React to `16.12.0` and since react `16.10` if I'm not wrong, react is throwing a warning message alerting about the future deprecation of the lifecycle methods 'componentWillUpdate' and others. 

The correct way to fix this it would be to replace this lifecycle with another if possible in `react-billboardjs` codebase. I think there is only one. Replacing will probably make more problems if it makes the logic to change.

The fastest way it would be to replace the name with the `UNSAFE_` prefix.

I'm out of time this days but I would find some time to do the fastest way for sure. 

What do you think about this @planttheidea ?

### PR DESCRIPTION
**Pull request by planttheidea**
Internally we use `componentWillUpdate` for updating the charts imperatively, however this is a depreciated lifecycle method as-of version 16.3. It will still be supported in React, but starting in version 17 only the `UNSAFE_` prefixed version will work.

This PR conditionally creates the method's name based on the React version used. This was done instead of changing wholesale the method name because the current version still supports React v15 and v16 below 16.3 (when the `UNSAFE_` prefix was introduced).

This should resolve #34 .

### CODE REVIEW

File: src/BillboardChart.js [hunk 1]
```diff
@@ -294,11 +291,11 @@ BillboardChart.defaultProps = {
 BillboardChart.getInstances = getInstances;
 
 export default createComponent(BillboardChart, {
+  [COMPONENT_WILL_UPDATE_NAME]: componentWillUpdate,
```
Comment (planttheidea) [inline src/BillboardChart.js]: Lots of noise in this file due to `prettier`, but this is the main change. The name is derived based on `React.version` at the top of this file.
